### ISSUE TITLE
P79页，正则表达式特殊字符贪婪模式与非贪婪模式表达有误

### ISSUE THREAD

**Issue by Mathhub6** [sfvsfv/Crawer#1]
![image](https://github.com/sfvsfv/Crawer/assets/96880842/886c8560-c601-446a-9475-25b4bf716a1e)

>在贪婪模式下，匹配器尽可能多地匹配符合要求的字符，直到不能再匹配为止。例如，正则表达式 a.*b 在匹配字符串 "abbcab" 时，会匹配整个字符串 "abbcab"，而不是期望的 "ab"。

>在非贪婪模式下，匹配器尽可能少地匹配符合要求的字符，直到满足要求为止。例如，正则表达式 a.*?b 在匹配字符串 "abbcab" 时，只会匹配到第一个 "ab"，而不是整个字符串。

**Comment by sfvsfv** [comment]
好的，感谢你的纠正
