### ISSUE TITLE
p92 段子爬取，第一页正则匹配好像没完全匹配上，只匹配到了17个，但是菜鸟工具看正则匹配到了20个

### ISSUE THREAD

**Issue by Mathhub6** [sfvsfv/Crawer#2]
https://xiaohua.zol.com.cn/baoxiaonannv/1.html

运行代码
```
# 导入模块
import logging

# 匹配内容
import re

# 网页请求
import requests

# 忽略警告
logging.captureWarnings(True)
# 控制时间
import time

# 写入请求网址与请求头
url = "https://xiaohua.zol.com.cn/baoxiaonannv/%d.html"
header = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36",
}


# 正则表达式
pattern = re.compile(r'<div class="summary-text">(.*?)</div>')


duanzi = url % (1)
print(duanzi)
requests.packages.urllib3.disable_warnings()
# 获取代码内容,cerify=False不认证
response = requests.get(url=duanzi, headers=header, verify=False, timeout=10).text
# 正则匹配
item = pattern.findall(response, re.S)
time.sleep(2)

response
# print(item)
```
![image](https://github.com/sfvsfv/Crawer/assets/96880842/dca6e547-5c83-4c8c-a656-c07fb7f6af0b)

通过正则表达式`<div class="summary-text">(.*?)</div>`照理来说应该这20个都匹配到了，但是为什么这3个没有匹配到?`re.S`似乎能含`\n`但是没有制表符`\t`。是这个问题吗？那正则表达式该怎么改使得`\t`也能被匹配
![image](https://github.com/sfvsfv/Crawer/assets/96880842/0ae46c4e-669d-4a0d-b0fe-7d89fde31798)
![image](https://github.com/sfvsfv/Crawer/assets/96880842/2d413a93-a51c-403a-a951-7a82aafc1fdc)

![image](https://github.com/sfvsfv/Crawer/assets/96880842/da07991e-b885-4faa-a5e2-754d2c67496e)
![image](https://github.com/sfvsfv/Crawer/assets/96880842/bcacbd04-c9ad-4e70-b427-cc8fba98f653)

![image](https://github.com/sfvsfv/Crawer/assets/96880842/aff17b21-ceac-4bec-99ea-8db64199c785)

**Comment by sfvsfv** [comment]
有没有看是哪个没有匹配上呢？然后对比下正则表达式
